const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_20_09_04_02_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjMyLFxuICAgICAgICAxMjEsXG4gICAgICAgIDIyNSxcbiAgICAgICAgODUsXG4gICAgICAgIDI2LFxuICAgICAgICA3MyxcbiAgICAgICAgMjIyLFxuICAgICAgICAxMjIsXG4gICAgICAgIDI2LFxuICAgICAgICA3NSxcbiAgICAgICAgOTEsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMzAsXG4gICAgICAgIDAsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTIyLFxuICAgICAgICA0NyxcbiAgICAgICAgMTk4LFxuICAgICAgICA0NyxcbiAgICAgICAgMTUxLFxuICAgICAgICA5NyxcbiAgICAgICAgMjUyLFxuICAgICAgICA3NixcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMjQsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMTgsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMjE2LFxuICAgICAgICAyMzYsXG4gICAgICAgIDEyNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3MCxcbiAgICAgICAgOTQsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTc5LFxuICAgICAgICA1NSxcbiAgICAgICAgMTE3LFxuICAgICAgICAxNjYsXG4gICAgICAgIDI1MixcbiAgICAgICAgMjI3LFxuICAgICAgICA4NCxcbiAgICAgICAgNjcsXG4gICAgICAgIDg0LFxuICAgICAgICAxNCxcbiAgICAgICAgMjU1LFxuICAgICAgICAxNzksXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjI2LFxuICAgICAgICAyMzUsXG4gICAgICAgIDI0LFxuICAgICAgICAyMjIsXG4gICAgICAgIDE5NixcbiAgICAgICAgMixcbiAgICAgICAgMTAxLFxuICAgICAgICAxODQsXG4gICAgICAgIDY1LFxuICAgICAgICAxNjksXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTEzLFxuICAgICAgICA5NixcbiAgICAgICAgMTczLFxuICAgICAgICAyNDksXG4gICAgICAgIDNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjEzLFxuICAgICAgICAxNzksXG4gICAgICAgIDEwNyxcbiAgICAgICAgNTMsXG4gICAgICAgIDM3LFxuICAgICAgICA1OCxcbiAgICAgICAgODEsXG4gICAgICAgIDE0MyxcbiAgICAgICAgODYsXG4gICAgICAgIDIwNSxcbiAgICAgICAgODksXG4gICAgICAgIDkxLFxuICAgICAgICA2MixcbiAgICAgICAgNyxcbiAgICAgICAgMTA4LFxuICAgICAgICAxNTksXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTk2LFxuICAgICAgICAyMzAsXG4gICAgICAgIDk2LFxuICAgICAgICAyNDQsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTYwLFxuICAgICAgICAzMCxcbiAgICAgICAgOTgsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMTcsXG4gICAgICAgIDk4LFxuICAgICAgICAxMzYsXG4gICAgICAgIDk0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTMzLFxuICAgICAgICAxNTIsXG4gICAgICAgIDc4LFxuICAgICAgICAxODAsXG4gICAgICAgIDEwMCxcbiAgICAgICAgNzEsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTY2LFxuICAgICAgICA5LFxuICAgICAgICA3NCxcbiAgICAgICAgMzcsXG4gICAgICAgIDIwNixcbiAgICAgICAgMjI0LFxuICAgICAgICAxMDMsXG4gICAgICAgIDIxLFxuICAgICAgICAxNzYsXG4gICAgICAgIDY4LFxuICAgICAgICA3NSxcbiAgICAgICAgMTQ1LFxuICAgICAgICA2MCxcbiAgICAgICAgMjQyLFxuICAgICAgICAyMCxcbiAgICAgICAgODksXG4gICAgICAgIDkyLFxuICAgICAgICAyOSxcbiAgICAgICAgMjExLFxuICAgICAgICAxNzksXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTg5LFxuICAgICAgICA3MCxcbiAgICAgICAgOTVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQ4LFxuICAgICAgICAxMjYsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTU1LFxuICAgICAgICA4OCxcbiAgICAgICAgMTAzLFxuICAgICAgICAxOTAsXG4gICAgICAgIDE5MyxcbiAgICAgICAgNDIsXG4gICAgICAgIDIwNCxcbiAgICAgICAgNTQsXG4gICAgICAgIDU4LFxuICAgICAgICAxNzgsXG4gICAgICAgIDIsXG4gICAgICAgIDMwLFxuICAgICAgICAxNTAsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTY0LFxuICAgICAgICAxOTAsXG4gICAgICAgIDE4MyxcbiAgICAgICAgODksXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTEzLFxuICAgICAgICAxOTAsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTc3LFxuICAgICAgICAxOTAsXG4gICAgICAgIDExLFxuICAgICAgICAzMCxcbiAgICAgICAgNDcsXG4gICAgICAgIDE1NSxcbiAgICAgICAgOTdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODUsXG4gICAgICAgIDEsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjMyLFxuICAgICAgICAyMDAsXG4gICAgICAgIDM5LFxuICAgICAgICAxNzcsXG4gICAgICAgIDExOCxcbiAgICAgICAgMjI1LFxuICAgICAgICAxMDUsXG4gICAgICAgIDIsXG4gICAgICAgIDExLFxuICAgICAgICA0NSxcbiAgICAgICAgMTksXG4gICAgICAgIDY2LFxuICAgICAgICA4MixcbiAgICAgICAgMTM0LFxuICAgICAgICAxODksXG4gICAgICAgIDE5NCxcbiAgICAgICAgNzAsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTI3LFxuICAgICAgICAxMzcsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMjYsXG4gICAgICAgIDQ5LFxuICAgICAgICAyNTQsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxNzUsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMzlcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDMsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMzcsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDEwOSxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICAxMzMsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDY2XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEwNixcbiAgICAgICAgICA2LFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICA1MyxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICA0MCxcbiAgICAgICAgICAyMixcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDEyMixcbiAgICAgICAgICAzLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAyMCxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgOCxcbiAgICAgICAgICAzN1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTAsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjksXG4gICAgICAgIDQzLFxuICAgICAgICAyNTIsXG4gICAgICAgIDEyMSxcbiAgICAgICAgNDQsXG4gICAgICAgIDE3MixcbiAgICAgICAgNjgsXG4gICAgICAgIDQyLFxuICAgICAgICAwLFxuICAgICAgICA1OSxcbiAgICAgICAgMTAzLFxuICAgICAgICAyMzEsXG4gICAgICAgIDE3LFxuICAgICAgICA4MixcbiAgICAgICAgNzcsXG4gICAgICAgIDEyNCxcbiAgICAgICAgOTcsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTQ2LFxuICAgICAgICAxMjQsXG4gICAgICAgIDk3LFxuICAgICAgICA0MSxcbiAgICAgICAgNDksXG4gICAgICAgIDI1LFxuICAgICAgICAyMTksXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTk1LFxuICAgICAgICAxMDIsXG4gICAgICAgIDExNSxcbiAgICAgICAgODAsXG4gICAgICAgIDExNCxcbiAgICAgICAgMjE2LFxuICAgICAgICAxMzEsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTIyLFxuICAgICAgICAyMjksXG4gICAgICAgIDIyMCxcbiAgICAgICAgNTUsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTE5LFxuICAgICAgICAxMjUsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTEwLFxuICAgICAgICAyNSxcbiAgICAgICAgMjM5LFxuICAgICAgICAxNDcsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjI3LFxuICAgICAgICA5MixcbiAgICAgICAgMTEzLFxuICAgICAgICAxNyxcbiAgICAgICAgMTc3LFxuICAgICAgICAyMzAsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTEwLFxuICAgICAgICAxMDMsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjE0LFxuICAgICAgICAxNSxcbiAgICAgICAgMzAsXG4gICAgICAgIDRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDE3OCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCIwL0VqUndmdzVWMU1ZU3MxMjZBRWNKd2NqUUFqRE9JczdjT2NSS29sY3FNPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzE5MzI0OTM2OUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiRkZCNkQ4MDZERkMwMTIyQTBGMzlFODhBQ0Y0MkEyNDRcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzQzNjI0NTcxXG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMTkzMjQ5MzY5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI1N0ZFQ0REQjIzNUE0NDk3ODAwMDJFNzhERUIyREM4OVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3NDM2MjQ1NzFcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiVmF6TFQ4UHlSb0N0MzNZeTdrV1NUQVwiLFxuICBcInBob25lSWRcIjogXCIyOGVlNDNkNS1lNGM0LTQ5ZWItYmVkZi1jOTg4OWM3MjQ2MDBcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNTQsXG4gICAgICAxMzYsXG4gICAgICA1MSxcbiAgICAgIDkyLFxuICAgICAgODksXG4gICAgICA5NCxcbiAgICAgIDE2NyxcbiAgICAgIDgyLFxuICAgICAgMTMsXG4gICAgICAxNTYsXG4gICAgICAxMjcsXG4gICAgICAyNCxcbiAgICAgIDMzLFxuICAgICAgMjA2LFxuICAgICAgMjQxLFxuICAgICAgMjM1LFxuICAgICAgMTMzLFxuICAgICAgMTAsXG4gICAgICA0LFxuICAgICAgNjRcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgOTMsXG4gICAgICAxMDksXG4gICAgICA4NSxcbiAgICAgIDQzLFxuICAgICAgMTc4LFxuICAgICAgODMsXG4gICAgICAyLFxuICAgICAgNDMsXG4gICAgICAxMDUsXG4gICAgICA5MSxcbiAgICAgIDI0MCxcbiAgICAgIDE0NSxcbiAgICAgIDY2LFxuICAgICAgMTk2LFxuICAgICAgNDQsXG4gICAgICAxMixcbiAgICAgIDE3NixcbiAgICAgIDc1LFxuICAgICAgMjUzLFxuICAgICAgMTcxXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIjQ1WEFDNk4zXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5MjMxOTMyNDkzNjk6MTBAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjMwODcyNzk1MzczNjg3OjEwQGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIlNpZ21hIPCfkbtcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNMUytwbWdROUxLMnZ3WVlBU0FBS0FBPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjNXUFlCZGhUdk10WEFJRHVJd25CbVdiNW11cHJsUDRWbU5Kcit3Tmp4RHM9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwibStmbWtPbkJpd1JDTnVieGlWSzM1NUQ4N3VuZ25xRmpMU0JFZkd1NE9CcVlIL0REa3A2cHpUa0t0MWFlZHdpRDVDZmk3TWYrSE9OOGp4RUhCenNqQnc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiNzN1N2QyUVpHdDg3Z2dlQTltQW1hVUQrdGR6NUxJdGtub0c5eCtLVkZseDdMamJpNVhDdDZ2NUhwV1dNSHVYbGJPaXJuVW0weFFtOVhodXRsTm5HRFE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTIzMTkzMjQ5MzY5OjEwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICA1LFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMjAzLFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICAzNSxcbiAgICAgICAgICA5LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICA1OVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzQzNjI0NTY4LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSEJaXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFIQlouanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI4azFFck5kQ1luRWhwaVhVNmJtZkg5V2RZUDRWaE41c3NZRGszTjBqMWJFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjIxODczNDM4OCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzQzNjI0NTY5NzU0XCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
